### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [nkfield/intro-data-capstone-biodiversity#1]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

You completed your code in codecademy platform, so I could not see your python work. All the numbers I can find from your presentation looks solid. So great work.

Presentation: Very nice presentation. I liked the color theme and clarity of each slide. I think your graphs look excellent. Also, your conclusions on the different statistical test were succinct and on point, so great work there. You presented the data as well as the results very nicely.

The sample size estimation is wrong. The answer from optimezely is 510. 
https://www.optimizely.com/sample-size-calculator/?conversion=15&effect=33.3&significance=90

Overall the recommendations are great. Excellent work overall.

**Comment by nkfield** [comment]
Hi! Thank you so much for reviewing my work, and for the friendly yet detailed feedback. I appreciate it all. Glad to hear that the extra time spent on design & clarity paid off!

Right, thank you about the sample size, and especially for the optimezely link, which will come in handy. I'm not sure how I got the wrong number, but clearly I did. 

Thanks again for looking through my work, and for the evaluation and correction. 

Best wishes,
Nick
